import type { Language } from './aiContract'
import type { PageSizeSpec, SlotShape } from './types'

export type MotifKind =
  | 'mandala'
  | 'paisley'
  | 'marigold'
  | 'rangoli'
  | 'diya'
  | 'kolam'
  | 'confetti'
  | 'pearl'
  | 'pookalam'
  | 'kasavu'
  | 'alpona'
  | 'peacock'
  | 'phulkari'
  | 'bandhani'
  | 'madhubani'
  | 'chikan'
  | 'ikat'
  | 'tile'

export interface Palette {
  /** Page background. */
  paper: string
  /** Secondary wash used for gradients / bands. */
  paperAlt: string
  ink: string
  inkSoft: string
  accent: string
  accentSoft: string
  gold: string
  /** Cover background. */
  cover: string
  coverAlt: string
  coverInk: string
}

export interface Theme {
  id: string
  name: string
  occasion: string
  /** Where in India this style comes from. */
  region: string
  /** One-line description shown in the picker. */
  blurb: string
  /** Script flourish printed on the cover, e.g. शुभ विवाह. */
  script: string
  defaultTitle: string
  closingLine: string
  closingScript: string
  palette: Palette
  motif: MotifKind
  /** Default photo frame shape for this theme. */
  shape: SlotShape
  titleFont: string
  bodyFont: string
  scriptFont: string
}

const SERIF = "'Cormorant Garamond', Georgia, 'Times New Roman', serif"
const DISPLAY = "'Marcellus', Georgia, serif"
const SANS = "'Mukta', 'Segoe UI', system-ui, sans-serif"
const DEVA = "'Tiro Devanagari Hindi', 'Noto Sans Devanagari', Georgia, serif"

/** The album prints regional captions in the family's own script. */
const SCRIPT_FONTS: Record<Language, string> = {
  telugu: "'Noto Serif Telugu', 'Gautami', Georgia, serif",
  english: SERIF,
  hindi: DEVA,
  marathi: DEVA,
  tamil: "'Noto Serif Tamil', 'Latha', Georgia, serif",
  kannada: "'Noto Serif Kannada', 'Tunga', Georgia, serif",
  malayalam: "'Noto Serif Malayalam', 'Kartika', Georgia, serif",
  bengali: "'Noto Serif Bengali', 'Vrinda', Georgia, serif",
  gujarati: "'Noto Serif Gujarati', 'Shruti', Georgia, serif",
  punjabi: "'Noto Serif Gurmukhi', 'Raavi', Georgia, serif",
}

export const scriptFontFor = (language: Language = 'english'): string =>
  SCRIPT_FONTS[language] ?? SCRIPT_FONTS.english

export const THEMES: Theme[] = [
  {
    id: 'tirupati-gold',
    region: 'Andhra & Telangana',
    name: 'Tirupati Saffron',
    occasion: 'Temple wedding',
    blurb: 'Saffron and heavy gold for a temple muhurtham, with mandala corners.',
    script: 'శుభమస్తు',
    defaultTitle: 'Our Wedding',
    closingLine: 'By His grace, and yours',
    closingScript: 'ధన్యవాదాలు',
    palette: {
      paper: '#fffaf0',
      paperAlt: '#fdedd2',
      ink: '#4a2508',
      inkSoft: '#9a6b35',
      accent: '#d4741a',
      accentSoft: '#eaa45c',
      gold: '#c69016',
      cover: '#b45b0c',
      coverAlt: '#6b3004',
      coverInk: '#fff0cf',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'seemantham',
    region: 'Andhra & Telangana',
    name: 'Seemantham',
    occasion: 'Baby shower',
    blurb: 'Soft rose and green for seemantham and valaikappu — bangles, flowers, blessings.',
    script: 'సీమంతం',
    defaultTitle: 'Seemantham',
    closingLine: 'Waiting for you',
    closingScript: 'ఆశీస్సులు',
    palette: {
      paper: '#fffaf9',
      paperAlt: '#fbe9ea',
      ink: '#40252c',
      inkSoft: '#94707a',
      accent: '#c4657c',
      accentSoft: '#e6a0ad',
      gold: '#c7a352',
      cover: '#b45a72',
      coverAlt: '#74314a',
      coverInk: '#fdeef0',
    },
    motif: 'pearl',
    shape: 'circle',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'upanayanam',
    region: 'South India',
    name: 'Upanayanam',
    occasion: 'Thread ceremony',
    blurb: 'Saffron and unbleached white for upanayanam, with kolam corners.',
    script: 'ఉపనయనం',
    defaultTitle: 'Upanayanam',
    closingLine: 'A beginning, in the old way',
    closingScript: 'శుభం',
    palette: {
      paper: '#fffdf6',
      paperAlt: '#f6efdd',
      ink: '#3d2a10',
      inkSoft: '#8c7549',
      accent: '#cc7a1f',
      accentSoft: '#e3a961',
      gold: '#bd9426',
      cover: '#c07a1c',
      coverAlt: '#7a4708',
      coverInk: '#fff6dd',
    },
    motif: 'kolam',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'shashtiabdapoorthi',
    region: 'South India',
    name: 'Shashtiabdapoorthi',
    occasion: 'Sixtieth birthday',
    blurb: 'Deep gold and maroon for a sixtieth — the second wedding, as families call it.',
    script: 'షష్టిపూర్తి',
    defaultTitle: 'Shashtiabdapoorthi',
    closingLine: 'Sixty years, and all of us here',
    closingScript: 'ఆయురారోగ్యం',
    palette: {
      paper: '#fdf8ec',
      paperAlt: '#f4e6c8',
      ink: '#3f1d14',
      inkSoft: '#8d6144',
      accent: '#8f2418',
      accentSoft: '#c2665a',
      gold: '#c49426',
      cover: '#7d1f14',
      coverAlt: '#400d07',
      coverInk: '#f9e7bc',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'chettinad-tile',
    region: 'Tamil Nadu',
    name: 'Chettinad Athangudi',
    occasion: 'Tamil wedding',
    blurb: 'Ivory, black and gold on the geometry of an Athangudi tile floor.',
    script: 'திருமணம்',
    defaultTitle: 'Our Wedding',
    closingLine: 'From our home to yours',
    closingScript: 'நன்றி',
    palette: {
      paper: '#fbf8f1',
      paperAlt: '#eee7d8',
      ink: '#1f1b16',
      inkSoft: '#6d6458',
      accent: '#1f1b16',
      accentSoft: '#8a7c63',
      gold: '#b8912c',
      cover: '#20201d',
      coverAlt: '#0b0b0a',
      coverInk: '#f2e6c8',
    },
    motif: 'tile',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.tamil,
  },
  {
    id: 'coorg-green',
    region: 'Karnataka',
    name: 'Kodava Coffee',
    occasion: 'Kodava wedding',
    blurb: 'Estate green and bronze for Kodagu weddings, where the hills are the backdrop.',
    script: 'ಮದುವೆ',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for coming up the hill',
    closingScript: 'ಧನ್ಯವಾದ',
    palette: {
      paper: '#f7f9f4',
      paperAlt: '#e3ecdc',
      ink: '#1c2e1c',
      inkSoft: '#587055',
      accent: '#35603a',
      accentSoft: '#7aa37c',
      gold: '#a8823a',
      cover: '#27492c',
      coverAlt: '#122414',
      coverInk: '#f0ecd2',
    },
    motif: 'paisley',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.kannada,
  },
  {
    id: 'rajputana-blue',
    region: 'Gujarat & Rajasthan',
    name: 'Rajputana Blue',
    occasion: 'Palace wedding',
    blurb: 'Jodhpur blue and gold, arched like a palace jharokha.',
    script: 'विवाह',
    defaultTitle: 'Our Wedding',
    closingLine: 'With gratitude from both families',
    closingScript: 'धन्यवाद',
    palette: {
      paper: '#f6f8fc',
      paperAlt: '#e2e9f5',
      ink: '#12224a',
      inkSoft: '#5a6a92',
      accent: '#1c3f8f',
      accentSoft: '#6f8bcb',
      gold: '#c9a227',
      cover: '#14306e',
      coverAlt: '#071736',
      coverInk: '#f6e6b8',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'awadhi-chikan',
    region: 'North India',
    name: 'Awadhi Chikankari',
    occasion: 'Nikah / wedding',
    blurb: 'White on white, the way Lucknow does it. Restraint as the whole point.',
    script: 'निकाह',
    defaultTitle: 'Our Nikah',
    closingLine: 'With our families, and yours',
    closingScript: 'शुक्रिया',
    palette: {
      paper: '#fbfbf9',
      paperAlt: '#eef0ec',
      ink: '#2b2f2c',
      inkSoft: '#77807a',
      accent: '#93a89b',
      accentSoft: '#c3d0c6',
      gold: '#b9a878',
      cover: '#e8ebe6',
      coverAlt: '#cdd3cb',
      coverInk: '#2b2f2c',
    },
    motif: 'chikan',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'madhubani',
    region: 'Bihar & Jharkhand',
    name: 'Mithila Madhubani',
    occasion: 'Maithil wedding',
    blurb: 'Madhubani line art on handmade paper — fish, vines and double outlines.',
    script: 'विवाह',
    defaultTitle: 'Our Wedding',
    closingLine: 'Blessings from Mithila',
    closingScript: 'धन्यवाद',
    palette: {
      paper: '#fdf6e6',
      paperAlt: '#f3e4c4',
      ink: '#2c1a0d',
      inkSoft: '#7d6444',
      accent: '#b23a1e',
      accentSoft: '#d9834f',
      gold: '#b8912c',
      cover: '#9c3216',
      coverAlt: '#57180a',
      coverInk: '#fbe9c8',
    },
    motif: 'madhubani',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'muga-silk',
    region: 'North East',
    name: 'Assam Muga',
    occasion: 'Assamese wedding',
    blurb: 'The warm gold of muga silk with a red gamosa border.',
    script: 'বিবাহ',
    defaultTitle: 'Our Wedding',
    closingLine: 'With love from both our homes',
    closingScript: 'ধন্যবাদ',
    palette: {
      paper: '#fdf9ec',
      paperAlt: '#f3e7c6',
      ink: '#3c2a10',
      inkSoft: '#8b7340',
      accent: '#b02a1f',
      accentSoft: '#d97a6a',
      gold: '#c19a2e',
      cover: '#9d7a1c',
      coverAlt: '#5c4409',
      coverInk: '#fdf1cf',
    },
    motif: 'ikat',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.bengali,
  },
  {
    id: 'sambalpuri-ikat',
    region: 'Odisha',
    name: 'Sambalpuri Ikat',
    occasion: 'Odia wedding',
    blurb: 'Ikat maroon, black and white — the feathered edge of a Sambalpuri weave.',
    script: '',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for being with us',
    closingScript: '',
    palette: {
      paper: '#fbf7f2',
      paperAlt: '#eee3d6',
      ink: '#241612',
      inkSoft: '#75604f',
      accent: '#8c1f1c',
      accentSoft: '#bf6360',
      gold: '#b8912c',
      cover: '#6f1715',
      coverAlt: '#340807',
      coverInk: '#f5e6cf',
    },
    motif: 'ikat',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SERIF,
  },
  {
    id: 'editorial-mono',
    region: 'Pan-India',
    name: 'Editorial Mono',
    occasion: 'Any occasion',
    blurb: 'Black, white and a great deal of air. The fashion-magazine album.',
    script: '',
    defaultTitle: 'The Wedding',
    closingLine: 'Thank you',
    closingScript: '',
    palette: {
      paper: '#ffffff',
      paperAlt: '#f4f4f4',
      ink: '#111111',
      inkSoft: '#767676',
      accent: '#111111',
      accentSoft: '#9a9a9a',
      gold: '#111111',
      cover: '#111111',
      coverAlt: '#000000',
      coverInk: '#ffffff',
    },
    motif: 'pearl',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SERIF,
  },
  {
    id: 'godavari',
    region: 'Andhra & Telangana',
    name: 'Godavari Pellikuthuru',
    occasion: 'Telugu wedding',
    blurb: 'River green, turmeric gold and kumkum red, with muggu corners — the Godavari districts.',
    script: 'పెళ్లి',
    defaultTitle: 'Maa Pelli',
    closingLine: 'With the blessings of both our families',
    closingScript: 'ధన్యవాదాలు',
    palette: {
      paper: '#fdfaf0',
      paperAlt: '#f0ead2',
      ink: '#26331b',
      inkSoft: '#6f7a54',
      accent: '#1f6b4f',
      accentSoft: '#63a583',
      gold: '#c79a1e',
      cover: '#17543e',
      coverAlt: '#0a2a1f',
      coverInk: '#f7e9bb',
    },
    motif: 'kolam',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'kalyanamandapam',
    region: 'Andhra & Telangana',
    name: 'Kalyana Mandapam',
    occasion: 'Telugu wedding',
    blurb: 'Kumkum red and heavy gold for the jeelakarra bellam and talambralu moments.',
    script: 'కళ్యాణం',
    defaultTitle: 'Our Kalyanam',
    closingLine: 'Thank you for blessing us',
    closingScript: 'నమస్కారం',
    palette: {
      paper: '#fdf5ee',
      paperAlt: '#f6e3cf',
      ink: '#40140f',
      inkSoft: '#916150',
      accent: '#a82116',
      accentSoft: '#d4695c',
      gold: '#c99420',
      cover: '#8d1a12',
      coverAlt: '#4a0905',
      coverInk: '#fbe6c2',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'bengali-lal',
    region: 'Bengal',
    name: 'Lal Paar',
    occasion: 'Bengali wedding',
    blurb: 'The red and white of a Bengali wedding, with alpona vines at the corners.',
    script: 'বিবাহ',
    defaultTitle: 'Our Wedding',
    closingLine: 'With love from both our families',
    closingScript: 'ধন্যবাদ',
    palette: {
      paper: '#fdf8f4',
      paperAlt: '#f6e2dc',
      ink: '#40120f',
      inkSoft: '#8f5b52',
      accent: '#c0221c',
      accentSoft: '#e0736b',
      gold: '#c79a35',
      cover: '#a8191a',
      coverAlt: '#5c0a0c',
      coverInk: '#fdf3e4',
    },
    motif: 'alpona',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.bengali,
  },
  {
    id: 'paithani',
    region: 'Maharashtra',
    name: 'Paithani Peacock',
    occasion: 'Marathi wedding',
    blurb: 'Paithani green and gold with a woven peacock — Marathi weddings and receptions.',
    script: 'लग्न',
    defaultTitle: 'Aamcha Lagna',
    closingLine: 'Thank you for being with us',
    closingScript: 'धन्यवाद',
    palette: {
      paper: '#f8f9f2',
      paperAlt: '#e6efdc',
      ink: '#123027',
      inkSoft: '#4f6d5f',
      accent: '#0d5f52',
      accentSoft: '#4f998b',
      gold: '#c2951f',
      cover: '#0c4a41',
      coverAlt: '#042420',
      coverInk: '#f5e8bd',
    },
    motif: 'peacock',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'phulkari',
    region: 'Punjab',
    name: 'Phulkari',
    occasion: 'Punjabi wedding',
    blurb: 'Phulkari pinks and marigold on ivory — anand karaj, chooda and a long night of bhangra.',
    script: 'ਵਿਆਹ',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for dancing with us',
    closingScript: 'ਧੰਨਵਾਦ',
    palette: {
      paper: '#fffaf2',
      paperAlt: '#fdeade',
      ink: '#44201f',
      inkSoft: '#94625c',
      accent: '#d4356b',
      accentSoft: '#f2874f',
      gold: '#d9a521',
      cover: '#c22a5e',
      coverAlt: '#7a1338',
      coverInk: '#fff0d5',
    },
    motif: 'phulkari',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: SCRIPT_FONTS.punjabi,
  },
  {
    id: 'bandhani',
    region: 'Gujarat & Rajasthan',
    name: 'Bandhani',
    occasion: 'Gujarati wedding',
    blurb: 'Bandhani red and saffron with mirror-bright dots — pithi, garba and the hastamelap.',
    script: 'લગ્ન',
    defaultTitle: 'Our Wedding',
    closingLine: 'With gratitude from both families',
    closingScript: 'આભાર',
    palette: {
      paper: '#fffaf0',
      paperAlt: '#fdeccd',
      ink: '#4a1f12',
      inkSoft: '#9a6440',
      accent: '#c8331f',
      accentSoft: '#ef8a3c',
      gold: '#d3a020',
      cover: '#b32a17',
      coverAlt: '#6a1208',
      coverInk: '#ffeecb',
    },
    motif: 'bandhani',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.gujarati,
  },
  {
    id: 'kanjeevaram',
    region: 'Tamil Nadu',
    name: 'Kanjeevaram Muhurtham',
    occasion: 'South Indian wedding',
    blurb: 'Kanjeevaram maroon and temple gold with kolam corners — the Tamil muhurtham album.',
    script: 'திருமணம்',
    defaultTitle: 'Our Muhurtham',
    closingLine: 'With the blessings of both families',
    closingScript: 'நன்றி',
    palette: {
      paper: '#fdf6ea',
      paperAlt: '#f3e3c8',
      ink: '#3d1013',
      inkSoft: '#8d5a45',
      accent: '#8c1b1f',
      accentSoft: '#c2565a',
      gold: '#c69218',
      cover: '#7c1417',
      coverAlt: '#43070b',
      coverInk: '#f8e6bd',
    },
    motif: 'kolam',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.tamil,
  },
  {
    id: 'pattu-jasmine',
    region: 'Andhra & Telangana',
    name: 'Pattu & Jasmine',
    occasion: 'South Indian wedding',
    blurb: 'Jasmine white, leaf green and gold — Telugu pellikuthuru and muhurtham mornings.',
    script: 'పెళ్లి',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for being with us',
    closingScript: 'ధన్యవాదాలు',
    palette: {
      paper: '#fcfbf3',
      paperAlt: '#eef2e0',
      ink: '#20331d',
      inkSoft: '#5f7355',
      accent: '#2f6b3f',
      accentSoft: '#76a87f',
      gold: '#c19b2b',
      cover: '#275c37',
      coverAlt: '#12301c',
      coverInk: '#f6f1d8',
    },
    motif: 'kolam',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.telugu,
  },
  {
    id: 'kasavu',
    region: 'Kerala',
    name: 'Kerala Kasavu',
    occasion: 'South Indian wedding',
    blurb: 'Off-white kasavu cloth with a woven gold border and pookalam corners.',
    script: 'വിവാഹം',
    defaultTitle: 'Our Wedding',
    closingLine: 'Gratefully, from both our homes',
    closingScript: 'നന്ദി',
    palette: {
      paper: '#fbf9f2',
      paperAlt: '#f2ecdb',
      ink: '#2a2a22',
      inkSoft: '#77705e',
      accent: '#9a7b21',
      accentSoft: '#c9ac5e',
      gold: '#bf9a2c',
      cover: '#efe6cd',
      coverAlt: '#d9c79b',
      coverInk: '#3a3124',
    },
    motif: 'kasavu',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.malayalam,
  },
  {
    id: 'mysore-silk',
    region: 'Karnataka',
    name: 'Mysore Silk',
    occasion: 'South Indian wedding',
    blurb: 'Royal purple Mysore silk with gold mandalas — Kannada weddings and receptions.',
    script: 'ಮದುವೆ',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for blessing us',
    closingScript: 'ಧನ್ಯವಾದಗಳು',
    palette: {
      paper: '#fbf7fb',
      paperAlt: '#eee2ee',
      ink: '#2e1a33',
      inkSoft: '#75597c',
      accent: '#5d2270',
      accentSoft: '#9a63ab',
      gold: '#c9a227',
      cover: '#4a1a5c',
      coverAlt: '#250a2f',
      coverInk: '#f6e5b9',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SCRIPT_FONTS.kannada,
  },
  {
    id: 'stage-reception',
    region: 'Pan-India',
    name: 'Stage Reception',
    occasion: 'South Indian reception',
    blurb: 'Charcoal and gold, wide frames and no fuss — built for stage and guest photos.',
    script: '',
    defaultTitle: 'Reception',
    closingLine: 'Thank you for celebrating with us',
    closingScript: '',
    palette: {
      paper: '#f8f7f5',
      paperAlt: '#e9e6e1',
      ink: '#1e1d1c',
      inkSoft: '#6c6862',
      accent: '#2f2c28',
      accentSoft: '#8a8279',
      gold: '#c2a24f',
      cover: '#191817',
      coverAlt: '#000000',
      coverInk: '#f0e5cd',
    },
    motif: 'pearl',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: SERIF,
  },
  {
    id: 'vivah-gold',
    region: 'North India',
    name: 'Royal Vivah',
    occasion: 'Wedding',
    blurb: 'Deep maroon, gold mandalas and arched frames — the classic North Indian wedding album.',
    script: 'शुभ विवाह',
    defaultTitle: 'Our Wedding',
    closingLine: 'Thank you for blessing our beginning',
    closingScript: 'धन्यवाद',
    palette: {
      paper: '#fbf4e8',
      paperAlt: '#f4e6cf',
      ink: '#3a1116',
      inkSoft: '#8a5c4a',
      accent: '#7a1220',
      accentSoft: '#b8535c',
      gold: '#c8972f',
      cover: '#6d0f1c',
      coverAlt: '#3d060f',
      coverInk: '#f6e3bb',
    },
    motif: 'mandala',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'marigold-mandap',
    region: 'North India',
    name: 'Marigold Mandap',
    occasion: 'Wedding',
    blurb: 'Genda-phool orange and temple red with garland borders. Warm and festive.',
    script: 'विवाह',
    defaultTitle: 'The Wedding',
    closingLine: 'With love and gratitude',
    closingScript: 'आभार',
    palette: {
      paper: '#fff6e6',
      paperAlt: '#ffe9c4',
      ink: '#52220b',
      inkSoft: '#9a6231',
      accent: '#d35400',
      accentSoft: '#f08a3c',
      gold: '#cf9b23',
      cover: '#c0390d',
      coverAlt: '#7c1f07',
      coverInk: '#ffeec9',
    },
    motif: 'marigold',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'dakshin-temple',
    region: 'South India',
    name: 'Dakshin Kalyanam',
    occasion: 'Wedding',
    blurb: 'Kanjeevaram gold-on-emerald with kolam corners — South Indian wedding styling.',
    script: 'कल्याणम्',
    defaultTitle: 'Our Kalyanam',
    closingLine: 'Blessed by family and friends',
    closingScript: 'नन्द्रि',
    palette: {
      paper: '#f6f7ef',
      paperAlt: '#e6efdf',
      ink: '#14301f',
      inkSoft: '#4c6b52',
      accent: '#0f5132',
      accentSoft: '#3f8f66',
      gold: '#b8912c',
      cover: '#0d4029',
      coverAlt: '#06251a',
      coverInk: '#f0e2b4',
    },
    motif: 'kolam',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'haldi-sun',
    region: 'Pan-India',
    name: 'Haldi Sunshine',
    occasion: 'Haldi',
    blurb: 'Turmeric yellow, bright and playful — perfect for haldi and pithi mornings.',
    script: 'हल्दी',
    defaultTitle: 'Haldi Ceremony',
    closingLine: 'A morning full of sunshine',
    closingScript: 'शुभम्',
    palette: {
      paper: '#fffbe9',
      paperAlt: '#fff2c0',
      ink: '#4a3505',
      inkSoft: '#97772a',
      accent: '#e0a800',
      accentSoft: '#f6c944',
      gold: '#c79100',
      cover: '#f0b400',
      coverAlt: '#c98000',
      coverInk: '#4a3505',
    },
    motif: 'marigold',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: DEVA,
  },
  {
    id: 'mehendi-green',
    region: 'Pan-India',
    name: 'Mehendi Night',
    occasion: 'Mehendi',
    blurb: 'Henna green with paisley vines curling around every frame.',
    script: 'मेहंदी',
    defaultTitle: 'Mehendi',
    closingLine: 'Stained hands, full hearts',
    closingScript: 'प्रेम',
    palette: {
      paper: '#f4f8ee',
      paperAlt: '#e3efd6',
      ink: '#1f3312',
      inkSoft: '#5b7546',
      accent: '#4f7a21',
      accentSoft: '#8bb35a',
      gold: '#a8892f',
      cover: '#2f5216',
      coverAlt: '#17300a',
      coverInk: '#eaf3d8',
    },
    motif: 'paisley',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'sangeet-night',
    region: 'Pan-India',
    name: 'Sangeet Midnight',
    occasion: 'Sangeet',
    blurb: 'Indigo night with gold sparkle — dancing, dhol and stage lights.',
    script: 'संगीत',
    defaultTitle: 'Sangeet Night',
    closingLine: 'We danced till the lights came on',
    closingScript: 'नृत्य',
    palette: {
      paper: '#f2f3fb',
      paperAlt: '#e0e3f5',
      ink: '#1b1f3f',
      inkSoft: '#5a5f85',
      accent: '#2f3a8f',
      accentSoft: '#6c78cf',
      gold: '#c9a227',
      cover: '#1b1f4b',
      coverAlt: '#0b0d24',
      coverInk: '#f1e2ae',
    },
    motif: 'confetti',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: DEVA,
  },
  {
    id: 'sagai-rose',
    region: 'Pan-India',
    name: 'Sagai Rose',
    occasion: 'Engagement',
    blurb: 'Blush rose and ivory with pearl detailing — soft and romantic.',
    script: 'सगाई',
    defaultTitle: 'Our Engagement',
    closingLine: 'The beginning of forever',
    closingScript: 'स्नेह',
    palette: {
      paper: '#fff8f7',
      paperAlt: '#fbe8e6',
      ink: '#4b2330',
      inkSoft: '#9a6b78',
      accent: '#b8566e',
      accentSoft: '#e0949f',
      gold: '#c9a66b',
      cover: '#a8455e',
      coverAlt: '#6c2338',
      coverInk: '#fde9ea',
    },
    motif: 'pearl',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'reception-ivory',
    region: 'Pan-India',
    name: 'Ivory Minimal',
    occasion: 'Reception',
    blurb: 'Clean ivory and charcoal with a single gold hairline. Lets the photos speak.',
    script: '',
    defaultTitle: 'Reception',
    closingLine: 'Thank you for celebrating with us',
    closingScript: '',
    palette: {
      paper: '#fcfaf6',
      paperAlt: '#f0ece3',
      ink: '#23211e',
      inkSoft: '#6e6a63',
      accent: '#3f3b35',
      accentSoft: '#8d867b',
      gold: '#b9a06a',
      cover: '#1f1d1a',
      coverAlt: '#111010',
      coverInk: '#f3ece0',
    },
    motif: 'pearl',
    shape: 'rect',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'naamkaran',
    region: 'Pan-India',
    name: 'Naamkaran Pastel',
    occasion: 'Baby / Naming',
    blurb: 'Soft pastels and tiny footprints — naamkaran, annaprashan and first birthdays.',
    script: 'नामकरण',
    defaultTitle: 'Naamkaran',
    closingLine: 'Our little blessing',
    closingScript: 'आशीर्वाद',
    palette: {
      paper: '#fdfaff',
      paperAlt: '#eef1fb',
      ink: '#2f3350',
      inkSoft: '#767b9c',
      accent: '#7b86d6',
      accentSoft: '#b3bbef',
      gold: '#c9b06b',
      cover: '#8e9ae0',
      coverAlt: '#5b67ac',
      coverInk: '#fdfbff',
    },
    motif: 'pearl',
    shape: 'circle',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: DEVA,
  },
  {
    id: 'birthday-confetti',
    region: 'Pan-India',
    name: 'Birthday Confetti',
    occasion: 'Birthday',
    blurb: 'Bright confetti bursts on cream — birthdays and anniversaries.',
    script: 'जन्मदिन',
    defaultTitle: 'Happy Birthday',
    closingLine: 'Here is to many more',
    closingScript: 'शुभकामनाएँ',
    palette: {
      paper: '#fffdf7',
      paperAlt: '#fdeee2',
      ink: '#3b2540',
      inkSoft: '#8a6d94',
      accent: '#e0417a',
      accentSoft: '#f78bab',
      gold: '#d8a92f',
      cover: '#d4326b',
      coverAlt: '#8d1c48',
      coverInk: '#fff3e2',
    },
    motif: 'confetti',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SANS,
    scriptFont: DEVA,
  },
  {
    id: 'griha-pravesh',
    region: 'Pan-India',
    name: 'Griha Pravesh',
    occasion: 'House warming',
    blurb: 'Terracotta and rangoli corners for griha pravesh and pooja days.',
    script: 'गृह प्रवेश',
    defaultTitle: 'Griha Pravesh',
    closingLine: 'May this home always be full',
    closingScript: 'शुभ लाभ',
    palette: {
      paper: '#fdf6ef',
      paperAlt: '#f6e4d4',
      ink: '#432114',
      inkSoft: '#8f6248',
      accent: '#b5502b',
      accentSoft: '#dd8b63',
      gold: '#c08b2c',
      cover: '#9c3d1d',
      coverAlt: '#5e2110',
      coverInk: '#fce7d1',
    },
    motif: 'rangoli',
    shape: 'arch',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
  {
    id: 'diwali-diya',
    region: 'Pan-India',
    name: 'Diwali Diya',
    occasion: 'Festival',
    blurb: 'Lamp-lit purple and amber for Diwali, Pongal, Onam and every festival at home.',
    script: 'शुभ दीपावली',
    defaultTitle: 'Festival Days',
    closingLine: 'Light, sweets and everyone home',
    closingScript: 'प्रकाश',
    palette: {
      paper: '#fdf7ef',
      paperAlt: '#f3e6e9',
      ink: '#31173a',
      inkSoft: '#7b5a86',
      accent: '#63267a',
      accentSoft: '#a566b8',
      gold: '#d9a52a',
      cover: '#41155a',
      coverAlt: '#1f0a2c',
      coverInk: '#f9e4b7',
    },
    motif: 'diya',
    shape: 'round',
    titleFont: DISPLAY,
    bodyFont: SERIF,
    scriptFont: DEVA,
  },
]

export const DEFAULT_THEME_ID = 'godavari'

export const themeById = (id: string): Theme =>
  THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? THEMES[0]

/** Regions in the order the picker shows them — the studio's own first. */
export const REGIONS = [
  'Andhra & Telangana',
  'Bihar & Jharkhand',
  'Odisha',
  'North East',
  'Tamil Nadu',
  'Karnataka',
  'Kerala',
  'North India',
  'Bengal',
  'Maharashtra',
  'Punjab',
  'Gujarat & Rajasthan',
  'South India',
  'Pan-India',
] as const

export const PAGE_SIZES: PageSizeSpec[] = [
  { id: 'sheet-12x36', label: 'Lay-flat spread 12 × 36 in', w: 36, h: 12 },
  { id: 'sheet-12x18', label: 'Album sheet 12 × 18 in', w: 18, h: 12 },
  { id: 'sq8', label: 'Square 8 × 8 in', w: 8, h: 8 },
  { id: 'sq12', label: 'Square 12 × 12 in (lay-flat)', w: 12, h: 12 },
  { id: 'land-a4', label: 'Landscape A4 (11.7 × 8.3 in)', w: 11.69, h: 8.27 },
  { id: 'port-a4', label: 'Portrait A4 (8.3 × 11.7 in)', w: 8.27, h: 11.69 },
  { id: 'land-10x8', label: 'Landscape 10 × 8 in', w: 10, h: 8 },
  { id: 'phone', label: 'Phone story (9 : 16)', w: 5.63, h: 10 },
]

export const pageSizeById = (id: string): PageSizeSpec => PAGE_SIZES.find((p) => p.id === id) ?? PAGE_SIZES[0]
