/* Downloads the album's webfonts into public/fonts and writes public/fonts/fonts.css,
   so the app (and its PDF rendering) works with no network. All four families are
   licensed under the SIL Open Font License 1.1. */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const FAMILIES = [
  'Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400',
  'Marcellus',
  'Mukta:wght@300;400;600;700',
  'Tiro+Devanagari+Hindi:ital@0;1',
  // South Indian scripts, for captions and chapter titles in the family's own language
  'Noto+Serif+Tamil:wght@400;600',
  'Noto+Serif+Telugu:wght@400;600',
  'Noto+Serif+Kannada:wght@400;600',
  'Noto+Serif+Malayalam:wght@400;600',
  // The rest of the country
  'Noto+Serif+Bengali:wght@400;600',
  'Noto+Serif+Gujarati:wght@400;600',
  'Noto+Serif+Gurmukhi:wght@400;600',
]

const OUT = new URL('../public/fonts/', import.meta.url).pathname
await mkdir(OUT, { recursive: true })

let css = `/* Self-hosted webfonts — SIL Open Font License 1.1.
   Cormorant Garamond (Catharsis Fonts), Marcellus (Astigmatic),
   Mukta (Ek Type), Tiro Devanagari Hindi (Indian Type Foundry),
   Noto Serif Tamil / Telugu / Kannada / Malayalam / Bengali / Gujarati /
   Gurmukhi (Google). Marathi uses Tiro Devanagari Hindi.
   Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n`

let n = 0
for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${family}: ${res.status}`)
  let sheet = await res.text()

  const urls = [...sheet.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1])
  for (const u of new Set(urls)) {
    const name = u.split('/').slice(-2).join('-').replace(/[^\w.-]/g, '')
    const bin = Buffer.from(await (await fetch(u, { headers: { 'User-Agent': UA } })).arrayBuffer())
    await writeFile(join(OUT, name), bin)
    sheet = sheet.split(u).join(`./${name}`)
    n++
  }
  css += `\n${sheet}`
}

await writeFile(join(OUT, 'fonts.css'), css)
console.log(`saved ${n} font files + fonts.css`)
